version: '3.8'

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/kanastra
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=your_email@gmail.com
      - SMTP_PASSWORD=your_email_password
      - FROM_EMAIL=your_email@gmail.com
    depends_on:
      - mongo
      - rabbitmq

  worker:
    build: .
    command: python /app/services/email_worker.py
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=your_email@gmail.com
      - SMTP_PASSWORD=your_email_password
      - FROM_EMAIL=your_email@gmail.com
    depends_on:
      - mongo
      - rabbitmq

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  mongo-data:
